language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

before_script:
  - composer global require hirak/prestissimo
  - composer install

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/php-coveralls --exclude-no-stmt

after_success:
  - coveralls