language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

before_script:
  - composer global require hirak/prestissimo
  - if  php -r "echo PHP_VERSION;" | grep -q "8.0" ; then composer install --ignore-platform-reqs; else composer install; fi;
  - composer dump-autoload --optimize

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - php vendor/bin/infection  --min-msi=99 --min-covered-msi=99

after_success:
  - php vendor/bin/php-coveralls --exclude-no-stmt

env: # important!
matrix:
  allow_failures:
  - php: nightly
